db:
  image: postgres:9.5
api:
  build: .
  command: bash -c "bundle install --local && bundle exec foreman start --env config/foreman/local.dev.env"
  env_file: config/foreman/local.dev.env
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
