class CreateCollections < ActiveRecord::Migration[5.1]
  def change
    create_table :collections, id: :uuid, default: 'gen_random_uuid()' do |t|
      t.uuid :user_id, null: false
      t.string :name, null: false, limit: 512
      t.timestamps
    end

    create_table :collection_memberships do |t|
      t.uuid :collection_id, null: false
      t.uuid :collectable_id
      t.string :collectable_type
    end

    # NB Rails' autogenerated name for this index is too long so we must specify our own
    add_index :collection_memberships, [:collectable_id, :collectable_type], name: 'collection_members_idx'

    add_foreign_key :collections, :users
    add_foreign_key :collection_memberships, :collections
  end
end
